Import all modes to highlightCode.js
MaxDesiatov/gatsby-remark-codemirror pull request #1
Opened 2019-06-27 12:14 UTC by NicolasStr

Why not adding all modes to highlightCode.js ?
There's no performance issue, because everything is done serverside when building.

2019-06-27 20:25 UTC, MaxDesiatov requested changes
This is great, thanks for the contribution @NicolasStr! I didn't know that `codemirror/mode/meta` can be imported to get all modes at the same time. I have a quick nitpicky request with regards to `let`/`const` use, but overall I think this can be easily merged after those are resolved.

2019-06-27 20:25 UTC, MaxDesiatov commented on highlightCode.js
> +  let required = `codemirror/mode/${mode}/${mode}`;
can this and `mode` be changed to `const`?

2019-06-28 06:00 UTC, NicolasStr commented
Yes, I didn't see it in ESLint, probably a misconfiguration on my side. This is now corrected!

2019-06-28 09:17 UTC, MaxDesiatov approved these changes

2019-06-28 09:18 UTC, merged

2019-06-28 17:13 UTC, NicolasStr commented
@MaxDesiatov Could you please tag a version ? I need to use this asap in production...

2019-06-28 17:18 UTC, MaxDesiatov commented
@NicolasStr no problem, that's now tagged and published on npm as 0.3.0

2019-06-28 17:30 UTC, NicolasStr commented
Thank you!